apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: my-api
  template:
    metadata:
      labels:
        app: my-api
    spec:
      containers:
      - name: api
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources: {{- toYaml .Values.resources | nindent 12 }}

