apiVersion: v1
kind: Service
metadata:
  name: my-api
spec:
  type: {{ .Values.service.type }}
  selector:
    app: my-api
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080

