name: Integration Test

on:
  workflow_dispatch:   # This triggers the workflow manually

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.4'

      # Step 3: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Install Helm
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      # Step 5: Install Kind (for local Kubernetes cluster)
      - name: Install Kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.19.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      # Step 6: Create a Kind Cluster
      - name: Create Kind cluster
        run: kind create cluster --name my-kind-cluster

      # Step 7: Build API Docker image
      - name: Build API Docker Image
        run: docker build -t my-api-image -f Dockerfile.api .

      # Step 8: Build Test Docker image
      - name: Build Test Docker Image
        run: docker build -t my-test-image -f Dockerfile.test .

      # Step 9: Load Docker images into Kind cluster
      - name: Load API Docker Image into Kind
        run: kind load docker-image my-api-image --name my-kind-cluster
      
      - name: Load Test Docker Image into Kind
        run: kind load docker-image my-test-image --name my-kind-cluster

      # Step 10: Deploy API using Helm
      - name: Deploy API
        run: helm install my-api ./my-api-chart

      # Step 11: Deploy the test pod
      - name: Deploy Test Pod
        run: kubectl apply -f test-pod.yaml

      # Step 12: Wait for the test pod to complete
      - name: Wait for Test Pod to Complete
        run: |
          kubectl wait --for=condition=complete --timeout=60s pod/api-test

      # Step 13: Retrieve test pod logs (for test results)
      - name: Get Test Pod Logs
        run: |
          kubectl logs api-test

